### ISSUE TITLE
Orientation interpolator typo?

### ISSUE THREAD

**Issue by zhuyifengzju** [StanfordVL/perls2#27]
I assume this line has a typo? I think it's supposed to be `self.prev_goal=self.goal`.

https://github.com/StanfordVL/perls2/blob/488421f75ccbd2278c1e319db2ef3686523bcfbc/perls2/controllers/interpolator/linear_ori_interpolator.py#L51

**Comment by rohun-kulkarni** [comment]
You're right. Thanks for catching this!

 Corrected in commit [4410372](https://github.com/StanfordVL/perls2/commit/441037243ded85fbed3422cdd69759963cdf52dd)
